### ISSUE TITLE
l just want get the detail page when l click the listview, but l don't need the title in the listview page. How can l remove the title?

### ISSUE THREAD

**Issue by weinengjian** [airbnb/native-navigation#126]

**Comment by weinengjian** [comment]
It is in the StackNavigator,and even  'navigationOptions.title'  you did not write. It still keep a row space in the page
![t2](https://user-images.githubusercontent.com/23124071/28037340-93d67c46-65ed-11e7-89cd-32a1a4a7d343.PNG)
![t1](https://user-images.githubusercontent.com/23124071/28037341-93dd7280-65ed-11e7-8d40-17426a11d29c.PNG)

**Comment by zobeirhamid** [comment]
The syntax you are using in the screenshot does not fit this package. I think you are using [react navigation]( https://github.com/react-community/react-navigation), so you can create an issue there.
But when I understood correctly, you want to hide the NavigationBar, to do that in react-navigation you have to set the header to null, so something like this:
```
MyHomeScreen.navigationOptions = {
  header: null
}
```

**Comment by weinengjian** [comment]
@zobeirhamid Thank you, it is work. I only don't need the title. 谢谢
