### ISSUE TITLE
Reload js not clear nav stack 

### ISSUE THREAD

**Issue by matpaul** [airbnb/native-navigation#128]
Hello all! There is an issue with reloading ->
I have screen component (CheckLogin) it make decision: show app or show login - so every time when i reload(dev mode) - all viewControllers in coordinator still exist and push one more.

**Comment by esam091** [comment]
JS reload only clears JS app state and view hierarchies created by React Native. The view controllers however, is not managed by React. They are managed by native code, so you should restore the navigation history by yourself before reloading.

**Comment by matpaul** [comment]
@esam091 yes, i understand - but in this issue i mean that we need some js function like StartNavigation that clear native stack)
