### ISSUE TITLE
Is this repository still maintained ?

### ISSUE THREAD

**Issue by arufian** [airbnb/native-navigation#163]
Hi, I would like to try this repo as my navigation for my next RN project. 

But the question is, since the shock news [about Airbnb dropped React Native](https://medium.com/airbnb-engineering/sunsetting-react-native-1868ba28e30a), is this repository still maintained ?

**Comment by listenzz** [comment]
#145 

It's dead

**Comment by arufian** [comment]
Ouch!  

thanks @listenzz
