### ISSUE TITLE
Support for modals

### ISSUE THREAD

**Issue by anonrig** [airbnb/native-navigation#30]
I was just curious if native-navigation will ever support modals just like react-native-navigation does? I couldn't see it in the documentation.

**Comment by eduardinni** [comment]
Yes, using this method: http://airbnb.io/native-navigation/docs/api/navigator/present.html

**Comment by browniefed** [comment]
![nativenav](https://cloud.githubusercontent.com/assets/1714673/23887636/62c0e5d4-0840-11e7-9fed-358234f8aa04.gif)
Example

**Comment by lelandrichardson** [comment]
As mentioned above, this is essentially what the "present" API is intended for. Closing this issue. Let me know if there's something more that you were asking about
