### ISSUE TITLE
"pod install" step missing 

### ISSUE THREAD

**Issue by rborn** [airbnb/native-navigation#45]
Following the install and run instructions for ios on a fresh cloned project will fail because the pods are not installed.
Once you run `cd example/ios && pod install` everything goes fine.

Thank you 😄

**Comment by orta** [comment]
I added this in #46

**Comment by rborn** [comment]
@orta I wonder if this isn't something that could be done in the npm script?

**Comment by JSafaiyeh** [comment]
Yeah it can easily be added in the npm script.

Something like:
`"install:ios": "bundle install --binstubs ./examples/ios; bundle exec pod install;`

**Comment by JSafaiyeh** [comment]
Submitted PR to @orta's fork to add the npm script. https://github.com/orta/native-navigation/pull/1

**Comment by timpler** [comment]
![image](https://cloud.githubusercontent.com/assets/7311462/23966761/e4e3dbc0-09bc-11e7-8e2d-c4b1b9227fa7.png)
I think it should be noted that you actualy need `pod`
