### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by nihgwu** [airbnb/native-navigation#57]
Someone don't want to use **CocoaPods** to change their project structure, **Carthage** is a much simpler alternative

**Comment by lelandrichardson** [comment]
@nihgwu thanks for bringing this up. I don't think there is anything actively preventing someone from using Carthage (though I'm not 100% sure). If you can figure this out, I'd love to add some instructions to the docs.

Without trying this myself, I think the main thing is that you might have to install both React and Native Navigation with carthage if you end up doing this, but I'm not sure.

Long term, the right solution might be to get React Native core to also add a dynamic framework target in addition to the static lib target, which I think could solve a lot of these issues.

**Comment by benkraus** [comment]
Carthage requires an xcodeproj, and a shared scheme, which this currently does not have that I can see. That would be the only thing needed to get Carthage support in, which I'd love to see. 

@lelandrichardson any reservations against adding an xcodeproj? I can submit a pull request pretty quickly for this.

**Comment by lelandrichardson** [comment]
@benkraus I don't have any problem with this. A PR would definitely be appreciated!

**Comment by benkraus** [comment]
How are you guys building the target currently?

**Comment by lelandrichardson** [comment]
@benkraus native-navigation is pulled in via cocoapods with a podspec in the example project currently

**Comment by benkraus** [comment]
Correct me if I am wrong, but from what I can gleam, `native-navigation` is being developed as a development pod from the example xcodeproj?

**Comment by lelandrichardson** [comment]
@benkraus that is correct

**Comment by emielvanliere** [comment]
Just wondering if anybody got this to work with Carthage already? Thanks!
