### ISSUE TITLE
Road to v1

### ISSUE THREAD

**Issue by benkraus** [airbnb/native-navigation#73]
What all needs to happen before the v1 milestone? I'd like to compile a list here (edit this comment), so that any contributors can have a list of tasks to choose from if they'd like to help. Perhaps the airbnb folks can get a project set up under the projects tab to track this better?

- [ ] Document all teh things
- [ ] Revisit installation steps, try to be dependency manager agnostic (#57, #57)
- [ ] ... much more

**Comment by rafayepes** [comment]
@benkraus did you duplicate #57 on purpose? 😜 

Could you provide some extra details regarding "much more"?

Are you already using the open source version of native-navigation in Airbnb already?

Thanks 😃

**Comment by skovhus** [comment]
Is this still a priority for airbnb?
