### ISSUE TITLE
Linking library after using native navigation gives error 

### ISSUE THREAD

**Issue by nak1b** [airbnb/native-navigation#77]
I was trying to install [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker) in the project thats already using native-navigation but it does not allow me to link the library. 
```
npm install react-native-image-picker@latest --save
react-native link

rnpm-install info Linking native-navigation android dependency 
rnpm-install info Android module native-navigation has been successfully linked 
rnpm-install info Linking native-navigation ios dependency 
rnpm-install ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/nakib/Desktop/project/peercel/node_modules/native-navigation/lib/ios/NativeNavigation.xcodeproj/project.pbxproj' 
Please file an issue here: https://github.com/facebook/react-native/issues 
```

I tried to install it manually but got different error in xcode 
`React/RCTBridgeModule.h file not found`

**Comment by nak1b** [comment]
I realize that i need to install the library as a pod package instead of linking the library via react-native link or manually installing it.

### Steps
```
npm install react-native-image-picker@latest --save

In the podfile add
pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

cd {yourproject}/ios
pod install
```

Now u should be able to use the library.

**Comment by flaviotobi** [comment]
i Want to install Realm, and i followed your steps, but still getting this error when i do pod install:

```
Fetching podspec for `realm` from `../node_modules/realm`
[!] No podspec found for `realm` in `../node_modules/realm`
```
