### ISSUE TITLE
Native Routing Required?

### ISSUE THREAD

**Issue by benkraus** [airbnb/native-navigation#78]
So I've been plugging along in my fork, adding `UISplitViewController` support, and it wasn't until just now I realized a flaw. I don't think flaw is the right word, because this was built for Airbnb's use case of integrating React Native into and existing app, but it is a flaw for those using this library in an app meant to be 100% React Native. 

What I noticed, is that it is impossible to push a `TabBar` component in React Native, as found in this library, and have it show the tab bar controller, without initializing a `ReactTabBarController` in Swift, and handling that natively.

Is there anything you would suggest for someone who wants to register a component as a tab bar controller and handle that in React Native entirely, rather than having to drop back into Swift to handle that routing?

**Comment by matpaul** [comment]
@benkraus Hi! Did you try to implement screen with tabBar to work without Native Code (ReactTabBarController) ?

**Comment by benkraus** [comment]
I did start down that path, yes. Nothing concrete yet, but I'll try and find some time to finish it up.
