### ISSUE TITLE
Difference to wix/react-native-navigation

### ISSUE THREAD

**Issue by nerdmed** [airbnb/native-navigation#80]
Dear Team,

the readme of the project states the following:

> Native Navigation is a navigation library for the React Native platform. There are many navigation libraries in the React Native ecosystem. Native Navigation is unique in that it is built on top of the iOS and Android platform navigational components, and is thus more "native" than most other options which implement navigation from scratch in JavaScript on top of base React Native components like View and Animated.

I am 100% with you that a native app just has to use the exiting native navigation solutions. Not some kind of _looks like original one_ navigation. But then you say that there is a library doing exactly that: 

> React Native Navigation by Wix engineering is an alternative library that uses "Native" navigation components of each platform, and has been around longer than Native Navigation.

For me its not obvious why you guys are creating an alternative to the existing solution? Do you have a different goal? Do you want to simplify it? What will be the key difference? I think it would help a lot of people if you could add this to your readme. It would motivate a lot to contribute to the project 👍 

Hope this helps. 

Peace

**Comment by brunolemos** [comment]
Hi @nerdmed, this is a duplicate of https://github.com/airbnb/native-navigation/issues/34,
please read the comments there and watch [this video](https://youtu.be/tWitQoPgs8w) for more details! Thanks.

**Comment by nerdmed** [comment]
@brunolemos oh thanks a lot, did not find it via the search - did not finish the video yet but maybe we should add the video to the readme 👍

**Comment by jameskhamil** [comment]
From my understanding, wix is being actively maintained, this is not

**Comment by nerdmed** [comment]
@jameskhamil @brunolemos honestly i am also really disappointed about the progress and news for this repo. Making so much noise about and the puff hiding for some month is not what we expected 🤒

**Comment by damathryx** [comment]
@nerdmed theres a discussion about this
https://github.com/airbnb/native-navigation/issues/114#issuecomment-303839307

**Comment by nerdmed** [comment]
@damathryx thx! Lets see where this is going.

**Comment by carlos-peru** [comment]
@jameskhamil @nerdmed @damathryx There's a move now to pass this project to the community https://github.com/airbnb/native-navigation/issues/145#issuecomment-332928351 and https://github.com/airbnb/native-navigation/issues/146
