### ISSUE TITLE
Is it possible to push a Native UIViewController on a Controller which has got React native component as subview?

### ISSUE THREAD

**Issue by vinayakparmar92** [airbnb/native-navigation#82]

**Comment by Kureev** [comment]
I may be wrong, but that's exactly how this library works. It wraps `RCTRootView` by `UIViewController` and manage them by using UINavigationController.

**Comment by vinayakparmar92** [comment]
@Kureev Thanks for the reply. I will try and get back

**Comment by irfanlone** [comment]
@vinayakparmar92 did you find any help with how to to push a Native UIViewController on the tabbar controller or any resources that show how to navigate from react native views to native views?
